//AUTH

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESSED = 'LOGIN_SUCCESSED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESSED = 'SIGNUP_SUCCESSED';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const CHECK_AUTH = 'CHECK_AUTH';

//USERS

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESSED = 'GET_ALL_USERS_SUCCESSED';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';
export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESSED = 'GET_USER_SUCCESSED';
export const GET_USER_FAILED = 'GET_USER_FAILED';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESSED = 'DELETE_USER_SUCCESSED';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESSED = 'UPDATE_USER_SUCCESSED';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
export const SET_USERS_LOADING = 'SET_USERS_LOADING';

//BOOKS

export const SET_BOOKS_LOADING = 'SET_BOOKS_LOADING';
export const GET_BOOKS = 'GET_BOOKS';
export const GET_AUTHORS = 'GET_AUTHORS';
export const GET_AUTHORS_SUCCESSED = 'GET_AUTHORS_SUCCESSED';
export const GET_BOOKS_SUCCESSED = 'GET_BOOKS_SUCCESSED';
