//AUTH

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESSED = 'LOGIN_SUCCESSED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESSED = 'SIGNUP_SUCCESSED';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const CHECK_AUTH = 'CHECK_AUTH';
export const CLEAR_AUTH = 'CLEAR_AUTH';

//USERS

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESSED = 'GET_ALL_USERS_SUCCESSED';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';
export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESSED = 'GET_USER_SUCCESSED';
export const GET_USER_FAILED = 'GET_USER_FAILED';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESSED = 'DELETE_USER_SUCCESSED';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESSED = 'UPDATE_USER_SUCCESSED';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
export const SET_USERS_LOADING = 'SET_USERS_LOADING';

//BOOKS

export const SET_BOOKS_LOADING = 'SET_BOOKS_LOADING';
export const GET_BOOKS = 'GET_BOOKS';
export const GET_AUTHORS = 'GET_AUTHORS';
export const GET_AUTHORS_SUCCESSED = 'GET_AUTHORS_SUCCESSED';
export const GET_BOOKS_SUCCESSED = 'GET_BOOKS_SUCCESSED';

//NEWS

export const SET_NEWS_LOADING = 'SET_NEWS_LOADING';
export const SET_NEWS_MODAL_STATUS = 'SET_NEWS_MODAL_STATUS';
export const GET_NEWS = 'GET_NEWS';
export const GET_ALL_NEWS_PAGINATED = 'GET_ALL_NEWS_PAGINATED';
export const DELETE_NEWS = 'DELETE_NEWS';
export const UPDATE_NEWS = 'UPDATE_NEWS';
export const CREATE_NEWS = 'CREATE_NEWS';
export const GET_NEWS_SUCCESSED = 'GET_NEWS_SUCCESSED';
export const GET_ALL_NEWS_PAGINATED_SUCCESSED = 'GET_ALL_NEWS_PAGINATED_SUCCESSED';
export const DELETE_NEWS_SUCCESSED = 'DELETE_NEWS_SUCCESSED';
export const UPDATE_NEWS_SUCCESSED = 'UPDATE_NEWS_SUCCESSED';
export const CREATE_NEWS_SUCCESSED = 'CREATE_NEWS_SUCCESSED';

//GALERIES

export const SET_GALERIES_LOADING = 'SET_GALERIES_LOADING';
export const SET_GALERIES_MODAL_STATUS = 'SET_GALERIES_MODAL_STATUS';
export const GET_GALERY = 'GET_GALERY';
export const GET_ALL_GALERIES_PAGINATED = 'GET_ALL_GALERIES_PAGINATED';
export const DELETE_GALERY = 'DELETE_GALERY';
export const UPDATE_GALERY = 'UPDATE_GALERY';
export const CREATE_GALERY = 'CREATE_GALERY';
export const GET_GALERY_SUCCESSED = 'GET_GALERY_SUCCESSED';
export const GET_ALL_GALERIES_PAGINATED_SUCCESSED = 'GET_ALL_GALERIES_PAGINATED_SUCCESSED';
export const DELETE_GALERY_SUCCESSED = 'DELETE_GALERY_SUCCESSED';
export const UPDATE_GALERY_SUCCESSED = 'UPDATE_GALERY_SUCCESSED';
export const CREATE_GALERY_SUCCESSED = 'CREATE_GALERY_SUCCESSED';

